// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Layout(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"fr\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/jarvisweb/templates/layout.templ`, Line: 9, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><script src=\"/static/htmx.min.js\"></script><style>\n\t\t\t\t:root { color-scheme: light dark; }\n\t\t\t\tbody { font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif; max-width: 860px; margin: 2rem auto; padding: 0 1rem; line-height: 1.5; }\n\t\t\t\th1 { font-size: 1.4rem; }\n\t\t\t\th3 { font-size: 1.05rem; margin-bottom: .3rem; }\n\t\t\t\t.card { border: 1px solid #8884; border-radius: 8px; padding: 1rem 1.25rem; margin: 1rem 0; }\n\t\t\t\tlabel { display: block; margin-bottom: .35rem; font-weight: 600; }\n\t\t\t\tselect, input[type=file] { display: block; margin-bottom: 1rem; }\n\t\t\t\tbutton { padding: .5rem 1rem; border-radius: 6px; border: 1px solid #8884; cursor: pointer; font-weight: 600; background: #8881; }\n\t\t\t\tbutton:hover { background: #8883; }\n\t\t\t\t.status-pending, .status-running { color: #a66; }\n\t\t\t\t.status-done { color: #2a2; }\n\t\t\t\t.status-failed { color: #c33; }\n\t\t\t\ttable { border-collapse: collapse; width: 100%; margin: .5rem 0 1rem; }\n\t\t\t\ttd, th { border: 1px solid #8884; padding: .4rem .6rem; text-align: left; font-size: .92rem; }\n\t\t\t\ttr.needs-review { background: #fffbe0; }\n\t\t\t\t.confidence { font-variant-numeric: tabular-nums; }\n\t\t\t\t.spinner { display: inline-block; width: 1em; height: 1em; border: 2px solid #8886; border-top-color: #555; border-radius: 50%; animation: spin 0.8s linear infinite; vertical-align: -0.15em; margin-right: .4em; }\n\t\t\t\t@keyframes spin { to { transform: rotate(360deg); } }\n\t\t\t\t.error-box { background: #fee2; border: 1px solid #c33; border-radius: 6px; padding: .75rem 1rem; color: #a33; }\n\t\t\t\t.muted { color: #888; font-size: .9rem; }\n\t\t\t</style></head><body><h1>Jarvis — extraction de documents</h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
